---
  - name: copy over app
    copy: 
      src: index_{{app_version}}.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
    notify: Restart apache service
  
 