---
- hosts: local
  connection: local
  gather_facts: False
  vars_files:
    - aws-vars.yml
    - aws_keys.yml
  tasks:
    - name : Create SG 
      ec2_group:
        name: "{{ security_group }}"
        description: ec2 group for ansible host
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
        state: present
    - name: Launch EC2 Instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        keypair:  "{{ keypair }}" 
        region: "{{ region}}"
        count: 1
      register: ec2
    
    - name: Add ip to hosts 
      add_host:
        name: "{{ item.public_ip }}"
        groups: appservers
      with_items: "{{ ec2.instances }}"

    - name: Add tag to Instance
      ec2_tag:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        resource: "{{ item.id }}" 
        region: "{{ region }}" 
        state: "present"
      with_items: "{{ ec2.instances }}"
      args:
        tags:
          Type: appservers
    
    - name: check for avaiablity
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        state: started
      with_items : "{{ ec2.instances }}"


# this will require key file
- hosts:  appservers
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Install apache
      yum: 
        name: httpd
        state: present
    - name: start enable httpd
      service:
        name:  httpd
        state: started
    - name: copy application files
      copy:
        src: /app-data/pragra-fronend/
        dest: /var/www/html/
        directory_mode: yes
