---
- name: Create User 
  hosts: app
  become: true
  tasks: 
   - name: Create user alex
     user:
       name: niyati
       state: present
       uid: 10001 
   - name:  Install NTP
     apt:
       name: ntp
       state: present
...
