---
- name: Intall Apache Server on Debian
  apt:
    name: apache2 
    state: present
  when: ansible_os_family == 'Debian'

- name: Install on Fedora/Redhat 
  yum:
    name: httpd
    state: present
  when: ansible_os_family =='Redhat'